AnimationPointers:
	table_width 2, AnimationPointers
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw FennekinAnimation
	dw BraixenAnimation
	dw DelphoxAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw HonchkrowAnimation
	dw MamoswineAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw EkansAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw ZangooseAnimation
	dw MunchlaxAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw PhantumpAnimation
	dw TrevenantAnimation
	dw DudunsparceAnimation
	dw ClodsireAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw DewpiderAnimation
	dw AraquanidAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw SeedotAnimation
	dw NuzleafAnimation
	dw ShiftryAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw InkayAnimation
	dw MalamarAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw SkrelpAnimation
	dw DragalgeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw TyruntAnimation
	dw TyrantrumAnimation
	dw YamaskAnimation
	dw CofagrigusAnimation
	dw FarigirafAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw RhyperiorAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw YanmegaAnimation
	dw GliscorAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw UrsalunaAnimation
	dw SuicasaurAnimation
	assert_table_length NUM_POKEMON
