BitmasksPointers:
	table_width 2, BitmasksPointers
	dw BulbasaurBitmasks
	dw IvysaurBitmasks
	dw VenusaurBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw CaterpieBitmasks
	dw MetapodBitmasks
	dw ButterfreeBitmasks
	dw FennekinBitmasks
	dw BraixenBitmasks
	dw DelphoxBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw HonchkrowBitmasks
	dw MamoswineBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw EkansBitmasks
	dw ArbokBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw MankeyBitmasks
	dw MunchlaxBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw VulpixBitmasks
	dw NinetalesBitmasks
	dw JigglypuffBitmasks
	dw WigglytuffBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw OddishBitmasks
	dw GloomBitmasks
	dw VileplumeBitmasks
	dw PhantumpBitmasks
	dw TrevenantBitmasks
	dw DudunsparceBitmasks
	dw ClodsireBitmasks
	dw DiglettBitmasks
	dw DugtrioBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw DewpiderBitmasks
	dw AraquanidBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw PoliwagBitmasks
	dw PoliwhirlBitmasks
	dw PoliwrathBitmasks
	dw AbraBitmasks
	dw KadabraBitmasks
	dw AlakazamBitmasks
	dw MachopBitmasks
	dw MachokeBitmasks
	dw MachampBitmasks
	dw TurtwigBitmasks
	dw GrotleBitmasks
	dw TorterraBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw GeodudeBitmasks
	dw GravelerBitmasks
	dw GolemBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw MagnezoneBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw PrimeapeBitmasks
	dw AnnihilapeBitmasks
	dw NoibatBitmasks
	dw MukBitmasks
	dw ShellderBitmasks
	dw CloysterBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw InkayBitmasks
	dw MalamarBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw SkrelpBitmasks
	dw DragalgeBitmasks
	dw ExeggcuteBitmasks
	dw ExeggutorBitmasks
	dw ImipupBitmasks
	dw SabrawlerBitmasks
	dw YamaskBitmasks
	dw CofagrigusBitmasks
	dw FarigirafBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw RhyhornBitmasks
	dw RhydonBitmasks
	dw ChanseyBitmasks
	dw RhyperiorBitmasks
	dw KangaskhanBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw ElectivireBitmasks
	dw MagmortarBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MrMimeBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw MagmarBitmasks
	dw YanmegaBitmasks
	dw GliscorBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw VaporeonBitmasks
	dw JolteonBitmasks
	dw FlareonBitmasks
	dw PorygonBitmasks
	dw AnorithBitmasks
	dw ArmaldoBitmasks
	dw KabutoBitmasks
	dw KabutopsBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw DratiniBitmasks
	dw DragonairBitmasks
	dw DragoniteBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw SentretBitmasks
	dw FurretBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw LedybaBitmasks
	dw LedianBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw LeafeonBitmasks
	dw GlaceonBitmasks
	dw SylveonBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw BellossomBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw PolitoedBitmasks
	dw GoomyBitmasks
	dw SliggooBitmasks
	dw GoodraBitmasks
	dw RanchorBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw EspeonBitmasks
	dw UmbreonBitmasks
	dw MurkrowBitmasks
	dw SlowkingBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw MismagiusBitmasks
	dw GirafarigBitmasks
	dw PinecoBitmasks
	dw ForretressBitmasks
	dw DunsparceBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw KleavorBitmasks
	dw TogekissBitmasks
	dw SpiritombBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw SlugmaBitmasks
	dw MagcargoBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw CursolaBitmasks
	dw KittringBitmasks
	dw CaterungBitmasks
	dw AbysseelBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw DreepyBitmasks
	dw DrakloakBitmasks
	dw DragapultBitmasks
	dw WeavileBitmasks
	dw Porygon_zBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw UrsalunaBitmasks
	dw WyrdeerBitmasks
	assert_table_length NUM_POKEMON
