FramesPointers:
	table_width 2, FramesPointers
	dw BulbasaurFrames
	dw IvysaurFrames
	dw VenusaurFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw CaterpieFrames
	dw MetapodFrames
	dw ButterfreeFrames
	dw FennekinFrames
	dw BraixenFrames
	dw DelphoxFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw HonchkrowFrames
	dw MamoswineFrames
	dw SwabluFrames
	dw AltariaFrames
	dw EkansFrames
	dw ArbokFrames
	dw PikachuFrames
	dw RaichuFrames
	dw ZangooseFrames
	dw MunchlaxFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw VulpixFrames
	dw NinetalesFrames
	dw JigglypuffFrames
	dw WigglytuffFrames
	dw ZubatFrames
	dw GolbatFrames
	dw OddishFrames
	dw GloomFrames
	dw VileplumeFrames
	dw PhantumpFrames
	dw TrevenantFrames
	dw DudunsparceFrames
	dw ClodsireFrames
	dw DiglettFrames
	dw DugtrioFrames
	dw MeowthFrames
	dw PersianFrames
	dw DewpiderFrames
	dw AraquanidFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw PoliwagFrames
	dw PoliwhirlFrames
	dw PoliwrathFrames
	dw AbraFrames
	dw KadabraFrames
	dw AlakazamFrames
	dw MachopFrames
	dw MachokeFrames
	dw MachampFrames
	dw TurtwigFrames
	dw GrotleFrames
	dw TorterraFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw GeodudeFrames
	dw GravelerFrames
	dw GolemFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw DoduoFrames
	dw DodrioFrames
	dw RioluFrames
	dw LucarioFrames
	dw GrimerFrames
	dw MukFrames
	dw ShellderFrames
	dw CloysterFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw OnixFrames
	dw InkayFrames
	dw MalamarFrames
	dw FeebasFrames
	dw MiloticFrames
	dw SkrelpFrames
	dw DragalgeFrames
	dw ExeggcuteFrames
	dw ExeggutorFrames
	dw TyruntFrames
	dw TyrantrumFrames
	dw YamaskFrames
	dw CofagrigusFrames
	dw FarigirafFrames
	dw KoffingFrames
	dw WeezingFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw ChanseyFrames
	dw RhyperiorFrames
	dw KangaskhanFrames
	dw HorseaFrames
	dw SeadraFrames
	dw ElectivireFrames
	dw MagmortarFrames
	dw StaryuFrames
	dw StarmieFrames
	dw MrMimeFrames
	dw ScytherFrames
	dw JynxFrames
	dw ElectabuzzFrames
	dw MagmarFrames
	dw YanmegaFrames
	dw GliscorFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw LaprasFrames
	dw DittoFrames
	dw EeveeFrames
	dw VaporeonFrames
	dw JolteonFrames
	dw FlareonFrames
	dw PorygonFrames
	dw AnorithFrames
	dw ArmaldoFrames
	dw KabutoFrames
	dw KabutopsFrames
	dw AerodactylFrames
	dw SnorlaxFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw DratiniFrames
	dw DragonairFrames
	dw DragoniteFrames
	dw MewtwoFrames
	dw MewFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw SentretFrames
	dw FurretFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw LedybaFrames
	dw LedianFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw CrobatFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw LeafeonFrames
	dw GlaceonFrames
	dw SylveonFrames
	dw TogepiFrames
	dw TogeticFrames
	dw NatuFrames
	dw XatuFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw BellossomFrames
	dw MarillFrames
	dw AzumarillFrames
	dw SudowoodoFrames
	dw PolitoedFrames
	dw GoomyFrames
	dw SliggooFrames
	dw GoodraFrames
	dw RanchorFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw YanmaFrames
	dw WooperFrames
	dw QuagsireFrames
	dw EspeonFrames
	dw UmbreonFrames
	dw MurkrowFrames
	dw SlowkingFrames
	dw MisdreavusFrames
	dw UnownFrames
	dw WobbuffetFrames
	dw GirafarigFrames
	dw PinecoFrames
	dw ForretressFrames
	dw DunsparceFrames
	dw GligarFrames
	dw SteelixFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw QwilfishFrames
	dw ScizorFrames
	dw ShuckleFrames
	dw HeracrossFrames
	dw SneaselFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw SlugmaFrames
	dw MagcargoFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw CorsolaFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw DelibirdFrames
	dw MantineFrames
	dw SkarmoryFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw KingdraFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw Porygon2Frames
	dw StantlerFrames
	dw SmeargleFrames
	dw TyrogueFrames
	dw HitmontopFrames
	dw SmoochumFrames
	dw ElekidFrames
	dw MagbyFrames
	dw MiltankFrames
	dw BlisseyFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw LugiaFrames
	dw HoOhFrames
	dw CelebiFrames
	dw UrsalunaFrames
	dw SuicasaurFrames
	assert_table_length NUM_POKEMON
